# Generated by Django 6.0.5 on 2026-05-27 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdelivery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
