# Generated by Django 6.0.5 on 2026-05-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0003_transportdelivery_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdelivery',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
