# Generated by Django 6.0.5 on 2026-05-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0004_transportdelivery_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_scheme_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
