# Generated by Django 6.0.5 on 2026-05-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0005_customer_employer_name_customer_is_scheme_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='next_of_kin_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
