# Generated by Django 6.0.5 on 2026-05-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0006_customer_next_of_kin_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nin',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
