# Generated by Django 6.0.5 on 2026-05-31 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0007_alter_customer_nin'),
        ('sales_app', '0004_pendingcreditsale_is_scheme_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositpayment',
            name='customer',
        ),
        migrations.AddField(
            model_name='depositpayment',
            name='pending_sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='sales_app.pendingcreditsale'),
        ),
    ]
