# Generated by Django 6.0.5 on 2026-05-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_alter_product_normal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='normal_percentage',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='normal_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
