# Generated by Django 6.0.5 on 2026-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_alter_product_normal_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Bag', 'Bag'), ('Piece', 'Piece'), ('Kg', 'Kg'), ('Roll', 'Roll'), ('Tonne', 'Tonne'), ('Length', 'Length'), ('Sheet', 'Sheet')], max_length=20),
        ),
    ]
