# Generated by Django 6.0.5 on 2026-05-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Bags', 'Bags'), ('Pieces', 'Pieces'), ('Kgs', 'Kgs'), ('Rolls', 'Rolls'), ('Tonnes', 'Tonnes'), ('Length', 'Length'), ('Sheets', 'Sheets')], max_length=20),
        ),
    ]
