# Generated by Django 6.0.5 on 2026-05-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='products_supplied',
            field=models.ManyToManyField(blank=True, to='inventory_app.product'),
        ),
    ]
