# Generated by Django 6.0.5 on 2026-05-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0007_supplier_products_supplied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='products_supplied',
        ),
    ]
