# Generated by Django 6.0.5 on 2026-05-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0009_stockentry_is_reversed_stockentry_reversal_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='is_reversed',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='reversal_reason',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='reversed_at',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='reversed_by',
        ),
    ]
