# Generated by Django 6.0.5 on 2026-05-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0010_remove_stockentry_is_reversed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eligible_for_scheme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
