# Generated by Django 6.0.5 on 2026-05-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
