# Generated by Django 6.0.5 on 2026-05-25 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pending_credit_sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_app.pendingcreditsale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='requires_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingcreditsale',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_credit_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
