# Generated by Django 6.0.5 on 2026-05-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_sale_pending_credit_sale_sale_requires_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='completed_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='deposit_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_sales', to='sales_app.pendingcreditsale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_source',
            field=models.CharField(choices=[('DIRECT', 'Direct Sale'), ('DEPOSIT', 'Deposit Completion')], default='DIRECT', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='transport_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
