# Generated by Django 6.0.5 on 2026-05-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0003_sale_completed_sale_sale_deposit_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcreditsale',
            name='is_scheme_order',
            field=models.BooleanField(default=True),
        ),
    ]
